# Generated by Django 3.1.2 on 2020-10-16 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец блога')),
            ],
            options={
                'verbose_name': 'Блог пользователя',
                'verbose_name_plural': 'Блоги пользователей',
            },
        ),
        migrations.CreateModel(
            name='NewsBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('news_text', models.TextField(blank=True, max_length=600, verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='blog.userblog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Новость блога',
                'verbose_name_plural': 'Новости блога',
                'ordering': ['-title', '-created_at'],
            },
        ),
    ]
