# Generated by Django 3.1.2 on 2020-10-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец блога'),
        ),
        migrations.AddField(
            model_name='newsblog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='newsblog',
            name='user_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='blog.userblog', verbose_name='Блог'),
        ),
    ]
