# Generated by Django 3.1.2 on 2020-10-18 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20201017_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Прочитано', to='blog.new')),
                ('subscriptions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Подписки')),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
